### ISSUE TITLE
Snake lengths are incorrect on first two turns.

### ISSUE THREAD

**Issue by bvanvugt** [battlesnakeio/board#69]
On turn 1 all snakes show length [1], and on turn 2 all snakes show length [2]. This is technically incorrect, as all snakes are length[3] at the start, they're just stacked on a single square.

After turn [3] they correctly display [3] until they eat food.

**Expected Behaviour:** Length should always be the number of body coordinates provided in the game state json.

**Comment by bvanvugt** [comment]
@hanneskuettner this may be of interest to you

**Comment by hanneskuettner** [comment]
Ah funny. Yeah I thought about what the correct way would be. Went with the wrong one then. I'll fix it later

**Comment by bvanvugt** [comment]
Yeah, it's interesting. [1] makes more sense as a viewer, but I think it's more important to match what the snake developers are seeing in code, and what number will be used for determining head-to-head collisions.

**Comment by hanneskuettner** [comment]
Another idea.
Maybe we can indicate both current visual length and the length next turn like this:

![image](https://user-images.githubusercontent.com/4376726/70327362-ef481280-1836-11ea-893f-1a7084a55e1c.png)

It adds a decent amount of visual clutter in the first two turns, but maybe thats okay.

![image](https://user-images.githubusercontent.com/4376726/70327463-23233800-1837-11ea-935d-cb4ae26af6d0.png)

I have an PR ready I just want to hear your input first.

**Comment by bvanvugt** [comment]
Hmm, I see what you're doing. 

As a spectator/caster, I think it adds complexity that would have to be explained, with not enough benefit to be worthwhile.

As a dev I like the perfect information but I don't NEED it, especially considering how safe those first two turns tend to be.

**Comment by bvanvugt** [comment]
@hanneskuettner have you got a PR (or a commit I can cherry pick) to address this? If so I'll get it live for Winter Classic on Saturday :)
